version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - importShadow
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 128
        rangeValCopy:
          sizeThreshold: 128
    gocyclo:
      min-complexity: 19
    goheader:
      template-path: hack/header.tpl
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    staticcheck:
      dot-import-whitelist:
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega/gstruct
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gocritic
          - mnd
        path: test/
      - linters:
          - dupl
          - gocritic
          - mnd
          - unparam
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
