/*
Copyright 2018 The nmstate Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// NodeNetConfPolicyListerExpansion allows custom methods to be added to
// NodeNetConfPolicyLister.
type NodeNetConfPolicyListerExpansion interface{}

// NodeNetConfPolicyNamespaceListerExpansion allows custom methods to be added to
// NodeNetConfPolicyNamespaceLister.
type NodeNetConfPolicyNamespaceListerExpansion interface{}

// NodeNetworkStateListerExpansion allows custom methods to be added to
// NodeNetworkStateLister.
type NodeNetworkStateListerExpansion interface{}

// NodeNetworkStateNamespaceListerExpansion allows custom methods to be added to
// NodeNetworkStateNamespaceLister.
type NodeNetworkStateNamespaceListerExpansion interface{}
