apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubernetes-nmstate.operatorNamespace" . }}
  labels:
    name: {{ include "kubernetes-nmstate.operatorNamespace" . }}
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
