---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: nmstate-operator
  namespace: {{ include "kubernetes-nmstate.operatorNamespace" . }}
  labels:
    nmstate.io: ""
    {{- include "kubernetes-nmstate.labels" . | nindent 4 }}
