apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: per-interface-ipv4-forwarding
spec:
  desiredState:
    interfaces:
      - name: eth1
        type: ethernet
        state: up
        ipv4:
          dhcp: true
          enabled: true
          forwarding: true
