/*
Copyright 2018 The nmstate Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	nmstateiov1 "github.com/nmstate/k8s-node-net-conf/pkg/apis/nmstate.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeNetConfPolicies implements NodeNetConfPolicyInterface
type FakeNodeNetConfPolicies struct {
	Fake *FakeNmstateV1
	ns   string
}

var nodenetconfpoliciesResource = schema.GroupVersionResource{Group: "nmstate.io", Version: "v1", Resource: "nodenetconfpolicies"}

var nodenetconfpoliciesKind = schema.GroupVersionKind{Group: "nmstate.io", Version: "v1", Kind: "NodeNetConfPolicy"}

// Get takes name of the nodeNetConfPolicy, and returns the corresponding nodeNetConfPolicy object, and an error if there is any.
func (c *FakeNodeNetConfPolicies) Get(name string, options v1.GetOptions) (result *nmstateiov1.NodeNetConfPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodenetconfpoliciesResource, c.ns, name), &nmstateiov1.NodeNetConfPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nmstateiov1.NodeNetConfPolicy), err
}

// List takes label and field selectors, and returns the list of NodeNetConfPolicies that match those selectors.
func (c *FakeNodeNetConfPolicies) List(opts v1.ListOptions) (result *nmstateiov1.NodeNetConfPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodenetconfpoliciesResource, nodenetconfpoliciesKind, c.ns, opts), &nmstateiov1.NodeNetConfPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nmstateiov1.NodeNetConfPolicyList{ListMeta: obj.(*nmstateiov1.NodeNetConfPolicyList).ListMeta}
	for _, item := range obj.(*nmstateiov1.NodeNetConfPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeNetConfPolicies.
func (c *FakeNodeNetConfPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodenetconfpoliciesResource, c.ns, opts))

}

// Create takes the representation of a nodeNetConfPolicy and creates it.  Returns the server's representation of the nodeNetConfPolicy, and an error, if there is any.
func (c *FakeNodeNetConfPolicies) Create(nodeNetConfPolicy *nmstateiov1.NodeNetConfPolicy) (result *nmstateiov1.NodeNetConfPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodenetconfpoliciesResource, c.ns, nodeNetConfPolicy), &nmstateiov1.NodeNetConfPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nmstateiov1.NodeNetConfPolicy), err
}

// Update takes the representation of a nodeNetConfPolicy and updates it. Returns the server's representation of the nodeNetConfPolicy, and an error, if there is any.
func (c *FakeNodeNetConfPolicies) Update(nodeNetConfPolicy *nmstateiov1.NodeNetConfPolicy) (result *nmstateiov1.NodeNetConfPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodenetconfpoliciesResource, c.ns, nodeNetConfPolicy), &nmstateiov1.NodeNetConfPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nmstateiov1.NodeNetConfPolicy), err
}

// Delete takes name of the nodeNetConfPolicy and deletes it. Returns an error if one occurs.
func (c *FakeNodeNetConfPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodenetconfpoliciesResource, c.ns, name), &nmstateiov1.NodeNetConfPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeNetConfPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodenetconfpoliciesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &nmstateiov1.NodeNetConfPolicyList{})
	return err
}

// Patch applies the patch and returns the patched nodeNetConfPolicy.
func (c *FakeNodeNetConfPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *nmstateiov1.NodeNetConfPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodenetconfpoliciesResource, c.ns, name, data, subresources...), &nmstateiov1.NodeNetConfPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nmstateiov1.NodeNetConfPolicy), err
}
