/*
Copyright 2018 The nmstate Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	nmstateiov1 "github.com/nmstate/k8s-node-net-conf/pkg/apis/nmstate.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeNetworkStates implements NodeNetworkStateInterface
type FakeNodeNetworkStates struct {
	Fake *FakeNmstateV1
	ns   string
}

var nodenetworkstatesResource = schema.GroupVersionResource{Group: "nmstate.io", Version: "v1", Resource: "nodenetworkstates"}

var nodenetworkstatesKind = schema.GroupVersionKind{Group: "nmstate.io", Version: "v1", Kind: "NodeNetworkState"}

// Get takes name of the nodeNetworkState, and returns the corresponding nodeNetworkState object, and an error if there is any.
func (c *FakeNodeNetworkStates) Get(name string, options v1.GetOptions) (result *nmstateiov1.NodeNetworkState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodenetworkstatesResource, c.ns, name), &nmstateiov1.NodeNetworkState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nmstateiov1.NodeNetworkState), err
}

// List takes label and field selectors, and returns the list of NodeNetworkStates that match those selectors.
func (c *FakeNodeNetworkStates) List(opts v1.ListOptions) (result *nmstateiov1.NodeNetworkStateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodenetworkstatesResource, nodenetworkstatesKind, c.ns, opts), &nmstateiov1.NodeNetworkStateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &nmstateiov1.NodeNetworkStateList{ListMeta: obj.(*nmstateiov1.NodeNetworkStateList).ListMeta}
	for _, item := range obj.(*nmstateiov1.NodeNetworkStateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeNetworkStates.
func (c *FakeNodeNetworkStates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodenetworkstatesResource, c.ns, opts))

}

// Create takes the representation of a nodeNetworkState and creates it.  Returns the server's representation of the nodeNetworkState, and an error, if there is any.
func (c *FakeNodeNetworkStates) Create(nodeNetworkState *nmstateiov1.NodeNetworkState) (result *nmstateiov1.NodeNetworkState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodenetworkstatesResource, c.ns, nodeNetworkState), &nmstateiov1.NodeNetworkState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nmstateiov1.NodeNetworkState), err
}

// Update takes the representation of a nodeNetworkState and updates it. Returns the server's representation of the nodeNetworkState, and an error, if there is any.
func (c *FakeNodeNetworkStates) Update(nodeNetworkState *nmstateiov1.NodeNetworkState) (result *nmstateiov1.NodeNetworkState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodenetworkstatesResource, c.ns, nodeNetworkState), &nmstateiov1.NodeNetworkState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nmstateiov1.NodeNetworkState), err
}

// Delete takes name of the nodeNetworkState and deletes it. Returns an error if one occurs.
func (c *FakeNodeNetworkStates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(nodenetworkstatesResource, c.ns, name), &nmstateiov1.NodeNetworkState{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeNetworkStates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodenetworkstatesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &nmstateiov1.NodeNetworkStateList{})
	return err
}

// Patch applies the patch and returns the patched nodeNetworkState.
func (c *FakeNodeNetworkStates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *nmstateiov1.NodeNetworkState, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodenetworkstatesResource, c.ns, name, data, subresources...), &nmstateiov1.NodeNetworkState{})

	if obj == nil {
		return nil, err
	}
	return obj.(*nmstateiov1.NodeNetworkState), err
}
