//go:build !ignore_autogenerated

/*
Copyright The Kubernetes NMState Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package shared

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastHeartbeatTime.DeepCopyInto(&out.LastHeartbeatTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ConditionList) DeepCopyInto(out *ConditionList) {
	{
		in := &in
		*out = make(ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionList.
func (in ConditionList) DeepCopy() ConditionList {
	if in == nil {
		return nil
	}
	out := new(ConditionList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NMStateDNSProbeConfiguration) DeepCopyInto(out *NMStateDNSProbeConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NMStateDNSProbeConfiguration.
func (in *NMStateDNSProbeConfiguration) DeepCopy() *NMStateDNSProbeConfiguration {
	if in == nil {
		return nil
	}
	out := new(NMStateDNSProbeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NMStateMetricsConfiguration) DeepCopyInto(out *NMStateMetricsConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NMStateMetricsConfiguration.
func (in *NMStateMetricsConfiguration) DeepCopy() *NMStateMetricsConfiguration {
	if in == nil {
		return nil
	}
	out := new(NMStateMetricsConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NMStateProbeConfiguration) DeepCopyInto(out *NMStateProbeConfiguration) {
	*out = *in
	out.DNS = in.DNS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NMStateProbeConfiguration.
func (in *NMStateProbeConfiguration) DeepCopy() *NMStateProbeConfiguration {
	if in == nil {
		return nil
	}
	out := new(NMStateProbeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NMStateSpec) DeepCopyInto(out *NMStateSpec) {
	*out = *in
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.InfraAffinity != nil {
		in, out := &in.InfraAffinity, &out.InfraAffinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InfraNodeSelector != nil {
		in, out := &in.InfraNodeSelector, &out.InfraNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InfraTolerations != nil {
		in, out := &in.InfraTolerations, &out.InfraTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelfSignConfiguration != nil {
		in, out := &in.SelfSignConfiguration, &out.SelfSignConfiguration
		*out = new(SelfSignConfiguration)
		**out = **in
	}
	out.ProbeConfiguration = in.ProbeConfiguration
	out.MetricsConfiguration = in.MetricsConfiguration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NMStateSpec.
func (in *NMStateSpec) DeepCopy() *NMStateSpec {
	if in == nil {
		return nil
	}
	out := new(NMStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NMStateStatus) DeepCopyInto(out *NMStateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NMStateStatus.
func (in *NMStateStatus) DeepCopy() *NMStateStatus {
	if in == nil {
		return nil
	}
	out := new(NMStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfigurationEnactmentCapturedState) DeepCopyInto(out *NodeNetworkConfigurationEnactmentCapturedState) {
	*out = *in
	in.State.DeepCopyInto(&out.State)
	in.MetaInfo.DeepCopyInto(&out.MetaInfo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfigurationEnactmentCapturedState.
func (in *NodeNetworkConfigurationEnactmentCapturedState) DeepCopy() *NodeNetworkConfigurationEnactmentCapturedState {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfigurationEnactmentCapturedState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfigurationEnactmentMetaInfo) DeepCopyInto(out *NodeNetworkConfigurationEnactmentMetaInfo) {
	*out = *in
	in.TimeStamp.DeepCopyInto(&out.TimeStamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfigurationEnactmentMetaInfo.
func (in *NodeNetworkConfigurationEnactmentMetaInfo) DeepCopy() *NodeNetworkConfigurationEnactmentMetaInfo {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfigurationEnactmentMetaInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfigurationEnactmentStatus) DeepCopyInto(out *NodeNetworkConfigurationEnactmentStatus) {
	*out = *in
	in.DesiredState.DeepCopyInto(&out.DesiredState)
	in.DesiredStateMetaInfo.DeepCopyInto(&out.DesiredStateMetaInfo)
	if in.CapturedStates != nil {
		in, out := &in.CapturedStates, &out.CapturedStates
		*out = make(map[string]NodeNetworkConfigurationEnactmentCapturedState, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RetryCount != nil {
		in, out := &in.RetryCount, &out.RetryCount
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfigurationEnactmentStatus.
func (in *NodeNetworkConfigurationEnactmentStatus) DeepCopy() *NodeNetworkConfigurationEnactmentStatus {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfigurationEnactmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfigurationPolicySpec) DeepCopyInto(out *NodeNetworkConfigurationPolicySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Capture != nil {
		in, out := &in.Capture, &out.Capture
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.DesiredState.DeepCopyInto(&out.DesiredState)
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfigurationPolicySpec.
func (in *NodeNetworkConfigurationPolicySpec) DeepCopy() *NodeNetworkConfigurationPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfigurationPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkConfigurationPolicyStatus) DeepCopyInto(out *NodeNetworkConfigurationPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnavailableNodeCountMap != nil {
		in, out := &in.UnavailableNodeCountMap, &out.UnavailableNodeCountMap
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastUnavailableNodeCountUpdate != nil {
		in, out := &in.LastUnavailableNodeCountUpdate, &out.LastUnavailableNodeCountUpdate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkConfigurationPolicyStatus.
func (in *NodeNetworkConfigurationPolicyStatus) DeepCopy() *NodeNetworkConfigurationPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkConfigurationPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkStateStatus) DeepCopyInto(out *NodeNetworkStateStatus) {
	*out = *in
	in.CurrentState.DeepCopyInto(&out.CurrentState)
	in.LastSuccessfulUpdateTime.DeepCopyInto(&out.LastSuccessfulUpdateTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkStateStatus.
func (in *NodeNetworkStateStatus) DeepCopy() *NodeNetworkStateStatus {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in RawState) DeepCopyInto(out *RawState) {
	{
		in := &in
		*out = make(RawState, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawState.
func (in RawState) DeepCopy() RawState {
	if in == nil {
		return nil
	}
	out := new(RawState)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfSignConfiguration) DeepCopyInto(out *SelfSignConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfSignConfiguration.
func (in *SelfSignConfiguration) DeepCopy() *SelfSignConfiguration {
	if in == nil {
		return nil
	}
	out := new(SelfSignConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *State) DeepCopyInto(out *State) {
	*out = *in
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = make(RawState, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new State.
func (in *State) DeepCopy() *State {
	if in == nil {
		return nil
	}
	out := new(State)
	in.DeepCopyInto(out)
	return out
}
