// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkState) DeepCopyInto(out *NodeNetworkState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkState.
func (in *NodeNetworkState) DeepCopy() *NodeNetworkState {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeNetworkState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkStateList) DeepCopyInto(out *NodeNetworkStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeNetworkState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkStateList.
func (in *NodeNetworkStateList) DeepCopy() *NodeNetworkStateList {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeNetworkStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkStateSpec) DeepCopyInto(out *NodeNetworkStateSpec) {
	*out = *in
	if in.DesiredState != nil {
		out.DesiredState = in.DesiredState.DeepCopyState()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkStateSpec.
func (in *NodeNetworkStateSpec) DeepCopy() *NodeNetworkStateSpec {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeNetworkStateStatus) DeepCopyInto(out *NodeNetworkStateStatus) {
	*out = *in
	if in.CurrentState != nil {
		out.CurrentState = in.CurrentState.DeepCopyState()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeNetworkStateStatus.
func (in *NodeNetworkStateStatus) DeepCopy() *NodeNetworkStateStatus {
	if in == nil {
		return nil
	}
	out := new(NodeNetworkStateStatus)
	in.DeepCopyInto(out)
	return out
}
