/*
Copyright 2018 The nmstate Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/nmstate/k8s-node-net-conf/pkg/apis/nmstate.io/v1"
	scheme "github.com/nmstate/k8s-node-net-conf/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeNetworkStatesGetter has a method to return a NodeNetworkStateInterface.
// A group's client should implement this interface.
type NodeNetworkStatesGetter interface {
	NodeNetworkStates(namespace string) NodeNetworkStateInterface
}

// NodeNetworkStateInterface has methods to work with NodeNetworkState resources.
type NodeNetworkStateInterface interface {
	Create(*v1.NodeNetworkState) (*v1.NodeNetworkState, error)
	Update(*v1.NodeNetworkState) (*v1.NodeNetworkState, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.NodeNetworkState, error)
	List(opts metav1.ListOptions) (*v1.NodeNetworkStateList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeNetworkState, err error)
	NodeNetworkStateExpansion
}

// nodeNetworkStates implements NodeNetworkStateInterface
type nodeNetworkStates struct {
	client rest.Interface
	ns     string
}

// newNodeNetworkStates returns a NodeNetworkStates
func newNodeNetworkStates(c *NmstateV1Client, namespace string) *nodeNetworkStates {
	return &nodeNetworkStates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeNetworkState, and returns the corresponding nodeNetworkState object, and an error if there is any.
func (c *nodeNetworkStates) Get(name string, options metav1.GetOptions) (result *v1.NodeNetworkState, err error) {
	result = &v1.NodeNetworkState{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodenetworkstates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeNetworkStates that match those selectors.
func (c *nodeNetworkStates) List(opts metav1.ListOptions) (result *v1.NodeNetworkStateList, err error) {
	result = &v1.NodeNetworkStateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodenetworkstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeNetworkStates.
func (c *nodeNetworkStates) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodenetworkstates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a nodeNetworkState and creates it.  Returns the server's representation of the nodeNetworkState, and an error, if there is any.
func (c *nodeNetworkStates) Create(nodeNetworkState *v1.NodeNetworkState) (result *v1.NodeNetworkState, err error) {
	result = &v1.NodeNetworkState{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodenetworkstates").
		Body(nodeNetworkState).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nodeNetworkState and updates it. Returns the server's representation of the nodeNetworkState, and an error, if there is any.
func (c *nodeNetworkStates) Update(nodeNetworkState *v1.NodeNetworkState) (result *v1.NodeNetworkState, err error) {
	result = &v1.NodeNetworkState{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodenetworkstates").
		Name(nodeNetworkState.Name).
		Body(nodeNetworkState).
		Do().
		Into(result)
	return
}

// Delete takes name of the nodeNetworkState and deletes it. Returns an error if one occurs.
func (c *nodeNetworkStates) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodenetworkstates").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeNetworkStates) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodenetworkstates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nodeNetworkState.
func (c *nodeNetworkStates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.NodeNetworkState, err error) {
	result = &v1.NodeNetworkState{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodenetworkstates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
